= Bionics: Brain-Computer Interfaces

This week we talked about many things, but the most interesting was BRAINIAC, a Brain-Computer interface that Professor LaCourse helped design. Brain-Computer Interfaces are all about allowing people to interact with and control computers hands free. This is obviously useful for those who suffer paralysis, but also has wider applications in neuroscience and the study of sleep

BRAINIAC works by using specific patterns in the brain to move and click a mouse pointer.

=== Mu waves

Mu waves occur when you _intend to move_, whether or not you actually move. Someone who is, for example, missing an arm can create Mu waves by trying to move their non-existent limb. Since each hemisphere of the brain controls motions on the opposite side of the body, attempting to move your right arm will generate a Mu wave which is perceptible on the left side of your head. Electrodes placed in front of and behind your ear, and slightly above it, have the best chance of capturing the wave, because that area is roughly associated with gross movement.

Mu waves are very periodic, much smoother than Alpha or Beta waves, which show up as very spiky, irregular patterns in ECGs.

=== Alpha waves

Alpha waves occur when you are awake, but have your eyes closed. They don't trigger when you blink, but only when you close your eyes deliberately. Because of this, they are perfect for detecting when someone wants to send an intentional signal. Alpha waves are best picked up with electrodes near the back of the skull.

=== Putting it all together

BRAINIAC uses Mu waves to move the mouse pointer back and forth, and Alpha waves to indicate a change of direction or a click. If the person using BRAINIAC tries to move their right arm, generating a left Mu wave, the mouse will move either right or up depending on the mode. Similarly, moving the left arm causes the mouse pointer to move left and down. Generating a brief pulse of Alpha waves causes a click, and generating a 3-second long burst switches the mouse pointer's direction of travel.

Using this system, experimental subjects were able to move the mouse around the screen and click on buttons quickly enough to click 7 buttons every minute, which while much slower than hoped, is still enough to allow, e.g. control of a room's lighting and temperature, or to allow very slow typing.

