= Verbal Smilies

One of the things I enjoy, but very rarely have the time to actually indulge in, is studying the design of languages. All languages are beautiful, in one way or another, but I often find myself particularly engaged by constructed languages (also known as link:https://conlang.org[conlangs], artificial languages, etc.).

One constructed language in particular that I think is really cool is link:https://lojban.org[Lojban]. Lojban (pronounced just like it's spelled, but always with a soft j) is a constructed language designed from the ground up to be easy to learn, and easy to use accross cultural barriers. Naturally, this makes it quite different from most natural languages, and there's still some debate as to whether they've sucseeded in this goal, but it's still a pretty cool language.

There are a bunch of cool features of Lojban I could talk about, but in this case, I want to pick just one, one that is often overlooked:

=== Attitudinals!

The name isn't very descriptive, honestly. Yes, they are words that describe attitudes, but there's more to them than that. Let's try that again.

=== Verbal Emoji!

This is a lot closer to the truth. Attitudinals are small words that look like this:

----
.ui
----

_.ui_, pronounced kind of like "Whee!" is an attitudinal that conveys happyness. By inserting _.ui_ into your sentences, you can indicate that you are particularly happy about the thing that the word follows, kind of like an adjective. Or, you can use _.ui_ all on it's own, to indicate general happyness.

_.ui_ doesn't have a direct English translation though. The closest might be "I'm happy!", but that doesn't really capture how _.ui_ can be used. 

Really, I think it's best to think of _.ui_ as a smile. Just like a smile, it can be inserted into the conversation without interrupting the meaning of the other words, and it doesn't seem as culturally awkward as walking up to someone and saying "I'm happy". Additionally, by making things like smiling explicit in Lojban, the language designers were able to clear up a lot of confusion that body language and tone could bring to a conversation when speaking with someone through text, or across a big cultural barrier, or even to an alien.

It's also important not to confuse _.ui_ with _.u'i_, which is pronounced like "Oooh, eee", and which indicates amusement. A lot of Lojban attitudinals contain an apostraphy, which in Lojban is pronunced a bit like a comma.

There are many attitudinals, of course, but I'm not going to just copy-and-paste a list from link:https://en.wikibooks.org/wiki/Lojban/Attitudinals[elsewhere on the internet], because that's just lazy. Instead, I'm going to hi-light what I think some of the most important are:

_cai_ (pronunced like "shy") is a word that strengthens attitudinals. It's a bit like adding "very" to "I'm happy", or like smiling broadly instead of just smiling. You tak _cai_ onto the end of whatever it's modifying, so a big smile would be translated into Lojban as _.uicai_ (pronounced: "Whee! shy").

_cai_ can be used with other attitudinals, of course, like _.uu_ (pronunced kind of like "wu"), which is pity or sympathy. _.uucai_ is like a sympathetic look, and a hand gently resting on someone's shoulder.

There's also another attitudinal modifier footnote:[There's a whole bunch. Go check out link:https://en.wikibooks.org/wiki/Lojban/Attitudinals[that link].] _nai_, which means the opposite. So _.uinai_ would be like a frown, and _.uicainai_ would be like a very big frown.

There's nowhere I'm really going with this, except to show you a cool idea that I've actually never seen anywhere else. It's a bit of a pity that attitudinals get eclipsed by the other features of Lojban when people come together to talk about the language.

I also think that it might be cool to try inserting attitudinals into your own conversations, at least with people in the know, or using them in place of emoji for ease of typing. I've barely scratched the surface of what attitudinals can convey (they also cover things like wants, categories of emotions, all the base emotions, combinations of emotions, agency, evidentiality, etc.), so go out, find some cool new words for emotions you never thought you'd be able to express in text, and use them to baffle your friends and befuddle your enemies. _.u'i_

As always, I'll see you next week. Suggestions for topics can be sent to link:mailto:setupminimal@gmail.com[my email]. Have a nice day! _.ui_