= Slavery

This week in History, we are discussing _The Long, Lingering Shadow_ by Robert J. Cottrol, about the history of slavery and racial inequality in the Americas.

It's really depressing. The fact that so many were held in bondage for so long is terrible.

But at least the demographics and cultural history are interesting! One thing that I didn't know prior to reading this book was how _different_ the treatment of free people of color in the United States was compared to the rest of the Americas. Cottrol argues that the relative population of white and black people shapes the general perception of how those people can engage in society.

For example, it was quite common during the 18th and 19th centuries for Africans to be seen as 'bestial' or 'savage'. This prejudice was common to all of the various countries and colonies of the Americas. As one unfortunate consequence of this in the United States people of African decent were presumed to be slaves footnote:[Well, they were presumed to be slaves in the Southern colonies. The Northern colonies each had their own rules and regulations concerning free black people, which generally worsened as time went on.], and often 'recaptured' and returned to bondage even if they were legally free. In contrast, Brazil, which had one of the more brutal and long-lasting regimes of slavery footnote:[They were the last country in the Americas to still have slavery.], recognized many possible paths to freedom for enslaved peoples, and recognized free persons of African decent as citizens and equal members of society.

Why this disparity? Cottrol hypothesizes that because there were many more free people of color footnote:[Mainly because of the remnants of _Las siete partidas_, a Spanish reinterpretation of Roman laws governing slavery that provided for many possible paths to legal freedom.] than Europeans in Brazil that they became normalized, and were not identified with the 'scary' native Africans.

This trend has been repeated many times with regards to different social justice issues; the more that a population is perceived to be part of the 'normal' functioning of society, the easier it is to accept in spite of the image disseminated by fear-mongers. Examples include not only acceptance of people of color, but also acceptance of people with different sexualities, and the growing acceptance of people with unexpected genders. I've noticed this trend before, but reading about it in the context of historical slavery drove home how deep-rooted this effect is.

I haven't yet finished the book, so I hope to have more commentary on it next week. I'll see you then.
